analyzer:
  errors:
    constant_identifier_names: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    invalid_use_of_protected_member: ignore
    invalid_use_of_visible_for_testing_member: ignore
    non_constant_identifier_names: ignore
    unrelated_type_equality_checks: ignore
    use_full_hex_values_for_flutter_colors: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    #    avoid_print: false
    prefer_single_quotes: true
    sort_constructors_first: false
    always_specify_types: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    prefer_relative_imports: true
