name: modern_player
description: Enhance your video playback experience with modern_player. A feature-rich Flutter package for flutter_vlc_player.
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  screen_brightness: ^2.1.7
  flutter_vlc_player: ^7.4.3
  youtube_explode_dart: ^2.5.2
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

